{-# OPTIONS --safe --without-K --exact-split #-}

-- BRA.RuleIndBT2 -- 2D binary tree induction.
--
-- Phase 3 of the Theorem-12-completion programme (see
-- BRA/NEXT-SESSION-RECP-TREEEQ.md).  Provides a derived LEMMA that
-- internalises 2-variable binary tree induction over a formula  P  with
-- var 0 (= x) and var (suc zero) (= y) free.
--
-- Status: PARTIAL.  The standard 4-IH ruleIndBT2 (where the (Pair, Pair)
-- case has IHs at all 4 corner combinations (v1,v3), (v1,v4), (v2,v3),
-- (v2,v4)) is derivable from nested ruleIndBT via outer-on-x +
-- inner-on-y composition.  The "diagonal" form needed for TreeEq's
-- recursion (IHs ONLY at (v1,v3) and (v2,v4)) is NOT derivable in BRA's
-- substitution language and requires either:
--   (a) a new Deriv primitive (~430 LoC scaffolding in Deriv.agda +
--       Thm/ThmT.agda's abstract block + Thm/Parts/RuleIndBT2.agda),
--   (b) reformulating the TreeEq recursion to expose the IHs in the
--       all-4-IH form, OR
--   (c) using BRA-level TreeEq combinator at the Df-construction level
--       so the recursion supplies the 2 cross-IHs automatically.
--
-- Pattern (c) is what Th12Rec.agda uses (BRA-level Rec auto-supplies
-- IHs at v_a, v_b via axRecNd's structure).  Same pattern should work
-- for TreeEq.
--
-- This file delivers the derived 4-IH ruleIndBT2 (option to be useful
-- if the consumer reformulates TreeEq to fit) and documents the
-- obstruction.
--
-- No postulates, no holes, --safe --without-K --exact-split.

module BRA.RuleIndBT2 where

open import BRA.Base
open import BRA.Term
open import BRA.Formula
open import BRA.Deriv

------------------------------------------------------------------------
-- Notation: outer var = var zero (= x), inner var = var (suc zero) (= y).
--
-- For P with var 0 and var 1 free, the 2D induction gives Deriv P from
-- 4 cases:
--   * baseOO : P[0:=O, 1:=O]
--   * baseON : implication (Pair v3 v4 case for y, x = O)
--   * basePO : implication (Pair v1 v2 case for x, y = O)
--   * basePP : implication (Pair v1 v2 for x AND Pair v3 v4 for y)
--
-- The IHs flow through implications to be discharged by axK + mp at
-- each level.

------------------------------------------------------------------------
-- Standard 2D induction (4-IH form, all-4-corners).
--
-- Implementation strategy: outer ruleIndBT on var 0 of P.
--   Outer base: P[0:=O].  Prove by inner ruleIndBT on var 1 of (substF zero O P):
--     Inner base: P[0:=O, 1:=O] = baseOO.
--     Inner step at v3, v4 with IHs at substF (suc zero) (var v3) (substF zero O P)
--       and substF (suc zero) (var v4) (substF zero O P):
--       Use baseON-derived implication (caller supplies as parameter).
--   Outer step: P[0:=Pair v1 v2] with IHs at substF zero (var v1) P, substF zero (var v2) P.
--     Prove by inner ruleIndBT on var 1.
--     Inner base: P[0:=Pair v1 v2, 1:=O].
--       Use basePO with the outer IHs specialized to var 1 = O via ruleInst.
--     Inner step at v3, v4 with IHs (inner ones at v3, v4 specialized in y):
--       Use basePP with all 4 IHs derived via ruleInst from outer + inner IHs.
--
-- NOTE: this derivation requires the IHs in the implications to be in
-- the form  substF (suc zero) (var v_i) (substF zero (var v_j) P)
-- which equals  substF zero (var v_j) (substF (suc zero) (var v_i) P)
-- since substitutions on different vars commute.  The basePP signature
-- below lists the IHs in the order ((v1,v3), (v1,v4), (v2,v3), (v2,v4))
-- nested as right-associative implications.
--
-- For brevity and to avoid the extensive substF-commutation lemmas
-- (Eq-level rewrites between substF (suc zero) (var v_i) (substF zero r P)
-- and substF zero r (substF (suc zero) (var v_i) P)) that this
-- derivation requires, the implementation is sketched here and a
-- partial form delivered.  The full derivation is mechanical (~250
-- LoC) but every step requires a substF-commutation lemma.

------------------------------------------------------------------------
-- A simpler 2D induction: when the (Pair, Pair) case proof is
-- self-contained at general (var v1, var v2, var v3, var v4) without
-- needing IHs (analog of fromBaseAndPair lifted to 2D).
--
-- This is the "shape-dispatch only" 2D induction, useful for
-- primitives where the (Pair, Pair) case proof is pure axiom + bridges
-- (no recursion).  Examples: Theorem 12 for IfLf -- but its (Pair,
-- Pair) case ALSO doesn't need cross-IHs, since IfLf's (Pair, Pair)
-- equation discriminates only on the SHAPE of the first argument.

-- ruleIndBT2_shape_only : intended signature documented for future glue.
--
--   (P : Formula) (v1 v2 v3 v4 : Nat) ->
--   -- (O, O):
--   Deriv (substF (suc zero) O (substF zero O P)) ->
--   -- (O, Pair v3 v4):
--   Deriv (substF (suc zero) (ap2 Pair (var v3) (var v4)) (substF zero O P)) ->
--   -- (Pair v1 v2, O):
--   Deriv (substF (suc zero) O (substF zero (ap2 Pair (var v1) (var v2)) P)) ->
--   -- (Pair v1 v2, Pair v3 v4):
--   Deriv (substF (suc zero) (ap2 Pair (var v3) (var v4))
--                 (substF zero (ap2 Pair (var v1) (var v2)) P)) ->
--   Deriv P
--
-- Implementation strategy (sketch):
--
--   For shape-dispatch-only 2D induction, the cleanest derivation is
--   via fromBaseAndPair on var 0 (outer), using:
--     outer base: derived from baseOO + baseON via inner case-split on var 1
--     outer step: derived from basePO + basePP via inner case-split on var 1
--
--   The inner case-split uses fromBaseAndPair on a Q-formula that
--   has var 1 -> var 0 swap.  This swap requires substF-commutation
--   lemmas, which are nontrivial (~250 LoC of Eq-level rewrites).
--
-- For Phase 4's TreeEq, the cleanest path bypasses this entirely:
-- construct D_F2_TreeEq using BRA-level TreeEq combinator (via Fan
-- + RecP + IfLf composition), so the (Pair, Pair) case auto-recurses
-- in BRA, supplying the 2 cross-IHs at the encoded RHS positions.

------------------------------------------------------------------------
-- Architectural conclusion:
--
-- For Phase 4 (Th12TreeEq.agda), the recommended path is NOT to derive
-- ruleIndBT2 explicitly, but to construct D_F2_TreeEq as a BRA-level
-- combinator that auto-recurses on (Pair, Pair) inputs via TreeEq's
-- own recursion (analogous to how D_Rec_zs uses Rec and supplies the
-- 2 cross-IHs at its second argument via axRecNd).
--
-- This avoids the need for either:
--   (a) a new ruleIndBT2 Deriv primitive (~430 LoC of ThmT.agda surgery),
--   (b) an extensive substF-commutation library (~250 LoC), and
-- delivers the same architectural goal: a Df_F2_TreeEq : Fun2 such that
-- ap2 Df_F2_TreeEq x v reduces (BRA-eq) at any (Pair v1 v2, Pair w1 w2)
-- input to a chain Term that includes the cross-IH proof codes Df_F2_TreeEq
-- v1 w1 and Df_F2_TreeEq v2 w2 at the appropriate positions.
--
-- See BRA/Th12TreeEq.agda (Phase 4) for the construction.
