{-# OPTIONS --safe --without-K --exact-split #-}

-- BRA.Thm12.TreeEqNN  --  Phase 7c TreeEq NN bridge (skeleton).
--
-- Constructs the three pieces required by  Parts.TreeEq.Construction :
--   D_TreeEq_NN_fun : Fun2
--   D_TreeEq_NN_closed : (x : Nat) (r : Term) ->
--     Eq (substF2 x r D_TreeEq_NN_fun) D_TreeEq_NN_fun
--   D_correct2_TreeEq_NN_pt : (p q a b : Term) ->
--     Deriv (atomic (eqn (ap1 thmT (ap2 D_TreeEq_NN_fun (Pair p q) (Pair a b)))
--                        (codeFTeq2_TreeEq (Pair p q) (Pair a b))))
--
-- This is a MUTUAL-RECURSION SKETCH: the NN_pt proof uses cross-IHs at
-- sub-pairs (p, a) and (q, b), which come from D_correct2_TreeEq itself
-- (Construction's universal proof).  Those IHs require closure args.
--
-- The clean instantiation is via a MUTUAL block that defines all four
-- (D_TreeEq_NN_fun, D_correct2_TreeEq_NN_pt, D_correct2_TreeEq_univ,
-- D_correct2_TreeEq) simultaneously.
--
-- This file is parametric: it takes the cross-IH at sub-pairs + sibling
-- IHs (D2 IfLf, D2 Pair) as PARAMETERS.  The instantiation site wires
-- them via the mutual recursion.

module BRA.Thm12.TreeEqNN where

open import BRA.Base
open import BRA.Term
open import BRA.Formula
open import BRA.Deriv
open import BRA.Cor
open import BRA.Thm.ThmT using (thmT)
open import BRA.Thm12.Parts.TreeEq using (codeFTeq2_TreeEq)
open import BRA.Thm12.Param.AxTreeEqNN using (parEncAxTreeEqNN)
open import BRA.Thm12.Param.CongL     using (parEncCongL)
open import BRA.Thm12.Param.CongR     using (parEncCongR)
open import BRA.Thm12.Param.RuleTrans using (parEncRuleTrans)

------------------------------------------------------------------------
-- The encoded chain produced by  D_TreeEq_NN_fun applied to
-- (Pair p q) (Pair a b).  Six sub-y's chained via parEncRuleTrans.
--
-- Sub-y's:
--   y1 = parEncAxTreeEqNN cor_p cor_q cor_a cor_b
--        (encodes  TreeEq (Pair cor_p cor_q) (Pair cor_a cor_b)
--                    = IfLf (TreeEq cor_p cor_a)
--                           (Pair (TreeEq cor_q cor_b) (Pair O O)))
--
--   y2 = parEncCongL IfLf yA xR
--        where  yA = encoded "TreeEq cor_p cor_a = cor (TreeEq p a)"
--        i.e.  yA  is the cross-IH at (p, a), supplied externally.
--
--   y3 = parEncCongR IfLf (parEncCongL Pair yB) xL
--        where  yB = encoded cross-IH at (q, b).
--
--   y4 = parEncCongR IfLf (parEncCongR Pair y_corOO) xL
--        where  y_corOO = encoded "Pair O O = cor (Pair O O)"
--        (built from corPairUnfold + axRecLf O stepCor).
--
--   y5 = parEncCongR IfLf y_PairLift x_outer
--        where  y_PairLift = encoded D_correct2_Pair at appropriate args
--        (lifts the inner Pair to cor of Pair).
--
--   y6 = y_IfLfLift
--        where  y_IfLfLift = encoded D_correct2_IfLf at appropriate args
--        (lifts the outer IfLf to cor of IfLf).
--
--   bridge = encoded  ruleSym (cong1 cor (axTreeEqNN p q a b))
--        (final BRA-level bridge).
--
-- Total chain: parEncRuleTrans of 7 sub-y's nested.
--
-- The Fun2 D_TreeEq_NN_fun must be a closed combinator expression that,
-- when applied to (Pair p q) (Pair a b), builds this chain.  Each y_i
-- depends on p, q, a, b via Fst/Snd extraction and cor application.

------------------------------------------------------------------------
-- Cross-IH abstraction: a function that, given (p, a), produces a Term
-- whose thmT-image is codeFTeq2_TreeEq p a.

CrossIHT : Set
CrossIHT = (p a : Term) -> Term

CrossIHCorrect : CrossIHT -> Set
CrossIHCorrect crossIH = (p a : Term) ->
  Deriv (atomic (eqn (ap1 thmT (crossIH p a))
                     (codeFTeq2_TreeEq p a)))

------------------------------------------------------------------------
-- Status: SKELETON only.
--
-- DESIGN OBSTRUCTION DISCOVERED 2026-04-27:
--
-- The natural NN bridge wants y_h_T (the Term feeding parEncCongL IfLf)
-- to BE  ap2 D_TreeEq p a  -- the actual ap2-application of the
-- universal D_TreeEq Fun2 to sub-pair components.  Its thmT-image is
-- codeFTeq2_TreeEq p a (= the cross-IH conclusion), which is what the
-- chain requires.
--
-- For D_TreeEq_NN_fun applied at (Pair p q, Pair a b) to PRODUCE a Term
-- containing  ap2 D_TreeEq p a , D_TreeEq_NN_fun's Fun2-expression must
-- embed D_TreeEq somewhere.  But D_TreeEq is constructed (in Parts/TreeEq.
-- Construction) FROM D_TreeEq_NN_fun.  The two are mutually recursive at
-- the Fun2-tree level -- which is structurally infinite (Fun2 is a
-- finite inductive type) and Agda rejects.
--
-- This is the fundamental "cross-IH structural circularity" obstruction.
-- It is NOT a glue-layer issue; it is a design-level constraint inherited
-- from Parts/TreeEq.Construction's parametric API.
--
-- Three resolution paths:
--
-- (R1) Reformulate Parts/TreeEq.Construction so that D_TreeEq_NN_fun
--      receives the cross-IH Term as a parameter (not constructs it).
--      Then  D_TreeEq_NN_fun cross_IH : Fun2  is supplied a CrossIHT,
--      and the chain embeds  cross_IH p a  as a Term coming from
--      outside.  Construction's universal proof passes the cross-IH
--      via ruleIndBT IH at sub-vars.  Significant Parts/TreeEq refactor.
--
-- (R2) Replace ap2 D_TreeEq p a in the chain with a "parEnc"-encoded
--      placeholder Term whose thmT-image equals codeFTeq2_TreeEq p a
--      provably.  No straightforward such Term known: parEncAxRefl
--      gives the symmetric "x = x" form, not the asymmetric one we need.
--
-- (R3) Make Parts/TreeEq.Construction NOT take D_TreeEq_NN_fun as a
--      parameter; instead, define the NN case directly inside Construction
--      via inline cross-IHs supplied from the outer ruleIndBT's
--      step-case premises (currently discharged via axK -- they would
--      be threaded via mp instead).
--
-- INVESTIGATION 2026-04-27 (R3 attempt -- LATER REVISED, see below):
--
-- R3 hits a deeper logical obstacle.  ruleIndBT's step-proof has type
--   Deriv ( IH(v1) imp ( IH(v2) imp Conclusion ) )
-- a SINGLE Deriv-level proof, NOT an Agda-level function.  To USE the
-- IHs inside the NN conclusion proof, we'd need to construct the
-- Deriv from a function  Deriv IH(v1) -> Deriv IH(v2) -> Deriv Conclusion
-- via the deduction theorem.
--
-- BRA's logic has axK + axS + mp -- full intuitionistic propositional
-- logic.  But the IH-threading proof uses  ruleInst (suc zero) (var v_inner) IH
-- to specialise the IH at sub-vars.  ruleInst is a META-RULE on
-- derivations:
--   ruleInst : (n : Nat) (t : Term) (P : Formula) ->
--              Deriv P -> Deriv (substF n t P)
--
-- Hilbert-encoding  lam IH. ruleInst n t P IH  as a Deriv would
-- require an AXIOM
--   axInstReplace : (P : Formula) (n : Nat) (t : Term) ->
--                   Deriv (P imp (substF n t P))
-- which is NOT in BRA.Deriv.  ruleInst is supplied as a rule precisely
-- to keep BRA's axiom set minimal.
--
-- WITHOUT this axiom, the NN-case IH-threading is NOT hilbert-encodable
-- using BRA's existing axioms.
--
-- THREE SUB-OPTIONS for R3:
--
-- (R3.a) ADD axInstReplace to BRA.Deriv as a new axiom.
--
--        ===== UNSOUND.  DEAD END.  DO NOT PURSUE.  (2026-04-28) =====
--
--        Original (incorrect) framing:  "Logically sound, corresponds
--        to a valid derivation rule turned into an axiom."  This was
--        wrong.
--
--        The proposed axiom is
--          axInstReplace : (P : Formula) (n : Nat) (t : Term) ->
--                          Deriv (P imp (substF n t P))
--        Counterexample to soundness:  let
--          P = atomic (eqn O (var 0)) ,  n = 0 ,  t = ap2 Pair O O .
--        Then  substF 0 t P = atomic (eqn O (ap2 Pair O O)) , whose
--        decoded statement  O = Pair O O  is FALSE in BRA's intended
--        model.  The implication  P imp substF 0 t P  is then
--          (O = var 0) imp (O = Pair O O) ,
--        which is false at  var 0 := O  (premise true, conclusion
--        false).  So  Deriv (P imp substF 0 t P)  would yield a
--        derivation of falsehood -- the axiom is unsound.
--
--        The valid meta-rule  ruleInst : Deriv P -> Deriv (substF n t P)
--        operates on already-derived (closed-context) judgments where
--        var n's universal-quantifier role is established by the
--        existence of the derivation.  Internalising it as an
--        implication strips that quantifier and forces the false
--        instance above.  This is the standard reason Hilbert systems
--        keep ruleInst as a meta-rule rather than an internal axiom.
--
--        Consequence for Theorem 12:  R3.a is OFF THE TABLE.  R1
--        (externalise CrossIHT via Agda mutual recursion) is the only
--        viable path that adds no Deriv axioms.  R3-revised (below)
--        relies on parEncRuleInst alone obviating cross-IHs; that
--        claim is unverified and now suspected wrong (parEncRuleInst
--        instantiates closed universal axioms at runtime args, but
--        the chain still needs cross-IH PROOFS to bridge sub-TreeEq's
--        -- those proofs must come from somewhere).
--
-- (R3.b) Sidestep ruleIndBT for D_correct2_TreeEq's universal proof.
--        Define the universal via Agda mutual recursion + Term pattern
--        matching, recursing on (Pair p q, Pair a b) -> (p, a) and
--        (q, b) directly.  Closure-arg propagation is a complication;
--        non-canonical Term cases (var, ap1, non-Pair ap2) need
--        separate handling (likely via a smaller "core" universal
--        Deriv proven without IH-threading).
--
-- (R3.c) Use a ruleIndBT VARIANT that takes IHs as Agda-level params:
--          ruleIndBT' : (P : Formula) (v1 v2 : Nat) ->
--                       Deriv (substF zero O P) ->
--                       (Deriv (substF zero (var v1) P) ->
--                        Deriv (substF zero (var v2) P) ->
--                        Deriv (substF zero (ap2 Pair (var v1) (var v2)) P)) ->
--                       Deriv P
--        This pushes the deduction-theorem burden into ruleIndBT itself,
--        which would need an internal SKI-encoding (still requiring
--        axInstReplace for the ruleInst uses inside) -- and so inherits
--        R3.a's unsoundness.  ALSO DEAD.
--
-- REVISED RECOMMENDATION (2026-04-28):  R1.  R3.a is unsound (see above);
-- R3.c reduces to R3.a; R3.b is messy with non-canonical Term cases.
-- R1 externalises the cross-IH builder via a CrossIHT parameter and
-- ties everything together via Agda-level mutual recursion in the
-- FromBridges instantiation site.  No new Deriv axioms.
--
-- R1 implementation sketch:
--   1. Refactor Parts/TreeEq.Construction to take CrossIHT +
--      CrossIHCorrect as parameters (NN_fun receives the cross-IH
--      builder; chain embeds  cross_IH p a  Terms supplied externally).
--   2. Analogous refactor for Parts/Rec and Parts/RecP step cases.
--   3. Build a Thm12NN.agda instantiation file with one  mutual  block
--      defining (D, D2, D_correct, D_correct2) simultaneously, where
--      the NN cases supply  CrossIHT = (\p a -> ap2 (D2 TreeEq) p a)  etc.
--   4. The Fun2 expressions stay finite; mutual recursion lives at the
--      Agda level only.
--
-- FILE LEFT AS DOCUMENTATION.  Decision: R1 (the others are dead).
--
-- =====================================================================
-- 2026-04-27 REVISION: PATH IS CLEARER.
--
-- ===== UNVERIFIED, AND NOW SUSPECTED INCORRECT.  (2026-04-28) =====
-- The revision below claims parEncRuleInst alone obviates cross-IH
-- threading.  This has not been validated by building any NN bridge.
-- The skepticism: parEncRuleInst lets you instantiate a CLOSED universal
-- axiom (e.g. encoded axTreeEqNN at fresh vars) at runtime arguments
-- (cor a1, cor b1, cor a2, cor b2).  But the chain still needs
-- encoded proofs of  TreeEq (cor a_i) (cor b_i) = cor (TreeEq a_i b_i)
-- at sub-pairs to fold the substituted RHS into  cor (TreeEq ... ) .
-- Those are cross-IH proofs; calling them "encoded substitutions"
-- doesn't make them appear from nowhere.  The substitution operation
-- replaces variables with terms, not  TreeEq  applications with their
-- cor-images.
--
-- Until a working NN bridge is built using parEncRuleInst alone, treat
-- the revision below as conjecture, not plan.  R1 (above) is the safer
-- path with no new Deriv axioms.
--
-- The revision (kept verbatim for reference):
--
-- The user's clarification + Guard p.16 reading shows Theorem 12 is a
-- META-CONSTRUCTION of proof codes, NOT an internal Hilbert derivation.
-- For the recursive (NN/successor) cases, Guard uses meta-level
-- substitution Sub(p, t) on proof codes -- corresponding to BRA's
-- ruleInst, but applied AT THE THMT LEVEL (Term-level encoding of
-- substitution on proof codes), not at the Deriv level.
--
-- BRA/Thm/ThmT.agda ALREADY HAS  body_ruleInst : Fun2  (line 1177).
-- Its operational behavior:
--   thmT (encoded form  ap2 Pair tagCode_ruleInst (ap2 Pair y_code t_code))
--     = encoded form of (substituted theorem)  via  body_ruleInst's  subT
--       sub-combinator (which performs Term-level substitution on proof codes).
--
-- So the missing piece is  BRA/Thm12/Param/RuleInst.agda  exposing:
--     parEncRuleInst : Term -> Term -> Term
--     parOutRuleInst : ...
--     parDispRuleInst : ...
-- analogous to all other  BRA/Thm12/Param/X.agda  wrappers.
--
-- WITH THIS IN PLACE, the recursive NN cases follow Guard's pattern:
--     D_Rec_zs (Pair a b) = parEncRuleInst (encoded universal axRecNd) (sub-payload (a, b))
--     thmT(...) = parOutRuleInst(...) = code(Rec(z,s)(Pair a b) = s(...))
--     bridge to code(Rec(z,s)(Pair a b) = cor(Rec(z,s)(Pair a b)))
--       via standard  cor -folding (same pattern as leaf bridges).
--
-- NO IH-threading or Hilbert-deduction needed.  The "cross-IH" intuition
-- from V4 was incorrect; the recursive case uses meta-Sub directly, not
-- a parEncRuleTrans + parEncCongL chain.
--
-- REVISED IMPLEMENTATION PLAN:
--   1. Write  BRA/Thm12/Param/RuleInst.agda  (~50 LoC) exposing
--      parEncRuleInst / parOutRuleInst / parDispRuleInst (calling
--      BRA.Thm.ThmT's existing thmTDispRuleInst_param if available, or
--      adding it analogously to the other _param wrappers).
--   2. Refactor  Parts/Rec.agda /  Parts/RecP.agda /  Parts/TreeEq.agda
--      Construction modules to expose D_Rec_NN_fun /  D_RecP_NN_fun /
--      D_TreeEq_NN_fun built via parEncRuleInst on the universal axiom
--      encoding (axRecNd / axRecPNd / axTreeEqNN as p.r. axiom codes).
--   3. NN_pt's proof becomes:  cong1 thmT (combinator-reduce-D_X_NN-to-
--      parEncRuleInst-form), then parDispRuleInst, then bridge via cor.
--   4. Phase 7 mutual block in BRA/Thm12.agda becomes well-founded:
--      the NN cases don't recurse on D2 / D, they substitute directly.
--
-- ESTIMATED COST:
--   Param/RuleInst.agda     ~50 LoC
--   Refactor Parts/Rec     ~150 LoC delta
--   Refactor Parts/RecP    ~150 LoC delta
--   Refactor Parts/TreeEq  ~250 LoC delta (NN case is 4-arg sub)
--   Plus minor Phase 7 glue updates.
--
-- TOTAL: ~600 LoC (much less than the ~2000 estimate that assumed
-- chain-of-cong-IHs).  Much more tractable.
--
-- NEXT-SESSION ACTION:  Investigate body_ruleInst's subT.  Check
-- whether thmTDispRuleInst_param exists in ThmT.agda (or needs to be
-- added analogously to thmTDispRuleIndBT_param).  Then write
-- Param/RuleInst.agda.
